### ISSUE TITLE
Rebuilding native dependencies sqlite3 hangs forever

### ISSUE THREAD

**Issue by yorublaireau** [bennymeg/nx-electron#147] opened 2022-03-23 22:21 UTC
**Describe the bug**

When trying to package a new app that contains sqlite3 with this nx workspaces, it hangs forever.

**To Reproduce**
Create a project from scratch, add sqlite3, and try building then packaging. The list of commands I've ran on a brand new project:
```
- npx create-nx-workspace@latest --preset=empty
- npm install --save-dev @nrwl/react
- nx g @nrwl/react:app ui
- npm i -D nx-electron@13.0.0-alpha.0
- npm i -D @angular-devkit/core @angular-devkit/schematics
- nx g nx-electron:app electron-app --frontendProject=ui
- npm i sqlite3
- nx build ui
- nx build electron-app
- nx package electron-app
```

**Expected behavior**
The electron app should finish packaging.

**Desktop (please complete the following information):**
 - OS: Windows 10 64 bits
 - Nx Electron Version: 13.0.0-alpha.0

**Additional context**
Here is the log when I run the last command:
```
nx run electron-app:package

*********************************************************
DO NOT FORGET TO REBUILD YOUR FRONTEND & BACKEND PROJECTS
FOR PRODUCTION BEFORE PACKAGING / MAKING YOUR ARTIFACT!
*********************************************************
  • electron-builder  version=22.14.13 os=10.0.19043
  • description is missed in the package.json  appPackageFile=D:\Projects\test2\package.json
  • author is missed in the package.json  appPackageFile=D:\Projects\test2\package.json
  • writing effective config  file=dist\packages\builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=sqlite3@5.0.2 platform=win32 arch=x64
```
I tried leaving it running for over 8 hours and it still didn't finish, so I doubt it's just taking a long time.

Let me know if I can help in any way.

**Comment by Luca8991** [comment] 2022-03-24 14:15
I have had the same problem since I added the [platform-folders](https://github.com/kingjan1999/platform-folders) npm package. Since this package needs to be built with [node-gyp](https://github.com/nodejs/node-gyp), I think the problem is [electron-builder](https://github.com/electron-userland/electron-builder) not handling well native dependencies.

I need help too!

**Comment by Luca8991** [comment] 2022-03-24 15:00
UPDATE:
If I execute the **package** command with `DEBUG=electron-builder`, I get this error:
```
execute command  command='C:\Program Files\nodejs\node.exe'
'C:\Users\me\AppData\Roaming\nvm\v16.14.1\node_modules\npm\bin\npx-cli.js' rebuild --verbose platform-folders@0.5.4 workingDirectory=
  ⨯ cannot execute  cause=exit status 1
                    out=You forgot to tell me what to run when the files changes!

                    command='C:\Program Files\nodejs\node.exe' 'C:\Users\me\AppData\Roaming\nvm\v16.14.1\node_modules\npm\bin\npx-cli.js' rebuild --verbose platform-folders@0.5.4
                    workingDir=
  • exited          command=app-builder.exe code=2 pid=46164
Error: C:\Users\me\code\simwin\monorepo\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
    at ChildProcess.<anonymous> (C:\Users\me\code\simwin\monorepo\node_modules\builder-util\src\util.ts:250:14)
    at Object.onceWrapper (node:events:646:26)
    at ChildProcess.emit (node:events:526:28)
    at ChildProcess.cp.emit (C:\Users\me\code\simwin\monorepo\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
```
which is the same obtained at https://github.com/electron-userland/electron-builder/issues/6411

**Comment by bennymeg** [comment] 2022-03-24 19:16
It seems like an issue with electron builder.
I am using its JavaScript API to build the app.
I didn't quite understand what causing the issue and how it can be fixed.
Please let me know if you find additional information on the topic.

**Comment by Luca8991** [comment] 2022-03-25 06:51
@bennymeg maybe this https://github.com/electron-userland/electron-builder/issues/2882#issuecomment-391740999 can help you

**Comment by yorublaireau** [comment] 2022-03-26 19:30
Looking at https://github.com/ytmdesktop/ytmdesktop/pull/924 it sounds like it's an issue with electron-builder and `npx`

using `npm exec nx package electron-app` seems to work instead

**Comment by Luca8991** [comment] 2022-03-26 20:21
It works! Thanks @yorublaireau!

Now I have another problem: the packaged application doesn't have the environment variables from `.env` file in the workspace. @bennymeg do you have some hints?

**Comment by bennymeg** [comment] 2022-03-28 12:06
@yorublaireau Great,
I will close this issue since it is related to electron builder, hopefully it will get fixed and I will update the dependency.

**Closed by bennymeg** 2022-03-28 12:06 UTC
