### ISSUE TITLE
wrong electron name when serving

### ISSUE THREAD

**Issue by esakal** [bennymeg/nx-electron#42] opened 2020-08-06 15:21 UTC
**Describe the bug**
Serving nx-electron application result with default app name `Electron`

**To Reproduce**
```
import { app, ipcRenderer } from 'electron';
export const appDataFolder = app.getPath('userData');
log.info(`set app data folder to '${appDataFolder}'`);
```

**Actual behavior**
userData is `/Users/eransakal/Library/Application Support/Electron`. Note that the path is using a default electron app name `Electron`

**Expected behavior**
userData should be `/Users/eransakal/Library/Application Support/MyCoolAppName` where `MyCoolAppName` is the name of the electron application.

**Desktop (please complete the following information):**
 - OS: Mac Catalina
 - Nx Electron Version nx-electron@9.3.2

**Comment by esakal** [comment] 2020-08-07 12:04
@bennymeg do you know how to resolve this one?

Thanks again for your extremely useful work!

**Comment by bennymeg** [comment] 2020-08-07 14:08
I am not sure, Ill have to run some tests.

Can you try setting `"productName": "MyCoolAppName",` in your `package.json'` and then invoke `app.getName()`?

**Comment by esakal** [comment] 2020-08-07 14:24
Thanks!
I tried setting productName both in the root package.json and on the nx-electron app folder but it didn't help.

I saw somewhere that if you run the `electron .` on the folder where the package.json exists it should work but I'm not sure if it applies to your library because it seems that you are running electron inside a node process.

![image](https://user-images.githubusercontent.com/4751797/89655378-b040f400-d8d2-11ea-8b88-fc80c35daee8.png)

**Comment by bennymeg** [comment] 2020-08-09 15:24
I have the same issue on windows (with angular / react).
According to the documentation is suppose to use the app name but it seems it always return Electron, even if the app name is different.

I would think that this is a bug in electron but its hard to believe they missed something like that.
I am not sure what to do next, any idea's?

**Comment by esakal** [comment] 2020-08-09 19:49
@bennymeg, does this help? https://stackoverflow.com/a/35643478

**Comment by bennymeg** [comment] 2020-08-10 07:15
Nice catch, that seems to be the problem.
Unfortunately, that's raises some issues:
 - NX works in a mono repo environment, that's way we it is reasonable to have multiple entry points in the repository (i.e. app + admin console) hence we can't use the main `package.json` to define the entry point. 
 - NX does not work well with multiple `package.json` files (like discussed in [here](https://github.com/nrwl/nx/issues/1777)) so I do not want to add one just for the app name, that will might be confusing.

**Comment by esakal** [comment] 2020-08-11 12:15
Hi!
Do you know if there are other ways to define the application name? I'm familiar with this one but there might be other ways. I know you can change the name thru the electron api but according to their documentation it will only change the name internally so it doesn't help us here.

The electron name is a must because this is the only way to get your own app data folder without colliding with other electron based applications. So I don't think we can keep it like that unless you aim only to frontend applications only with minimal/none os api interactions.

But I have a question. It seems that react library does create package.json per library when needed [blog link](https://blog.nrwl.io/support-for-publishable-react-libraries-updated-dependency-graph-and-more-in-nx-8-6-63510075a522) so there is a precedence. I don't think having a package.json file with only a name will affect other nx scripts / behaviours.  

How about having a flag like in react ``--publishable`` flag  that if provided will add that package.json file?

**Comment by bennymeg** [comment] 2020-08-16 16:50
I am a bit busy so it might take some time.
I think I have a solution for this problem, its not perfect, but it will work. Ill update when Ill get to it.

**Comment by esakal** [comment] 2020-09-19 18:51
@bennymeg Hi! did you have luck with that one? 

I think there is another reason to use it. It appears that the name affect also the registration in key chain so if you try to store passwords with the keychain it will attach it to the general electron app which means that it will share credentials between applications

Do you have an idea how to solve this one?

**Comment by bennymeg** [comment] 2020-10-19 16:19
No luck so far.. =\

I will suggest for now this dirty hack:
```
let userDataPath = app.getPath('userData').replace(/\/electron$/, app.getName());
```

**Comment by SolarIceMedia** [comment] 2020-11-07 18:36
there is a way to do it if its using electron-builder. I'm not well versed in the javascript field I'm just learning (I mostly do c#) but this link mentions a second way to set the app name:

https://www.electron.build/configuration/configuration

could possible be as simple as putting a electron-builder.yml in the root dir of the app ? not sure if it picks it up by default or you have to use the --options thing it mentions

**Comment by bennymeg** [comment] 2020-11-08 11:19
Thanks, but the issue is occurring only in the development process while serving the app.

**Comment by SolarIceMedia** [comment] 2020-11-08 19:31
oh well that's easy, its how electron works. during dev it doesn't do like normal I have no idea why. even in a non mono repo setup where the only application is an electron app (using vue) and its sitting right next to the package.json file, if I log out app.name it shows Electron. the only thing you can do is in the main process file (the one that creates the browser window) is check the NODE_ENV and if its anything other than production manually set the name.

its not an issue with this, its a general electron thing. it only reads the package.json during production build. I have no idea why

**Comment by bennymeg** [comment] 2020-11-08 20:54
@SolarIceMedia Thank you for clarifying that. I does not seems like it is the desired behavior, it is probably worth mentioning it in the electron repository. 

I will close this issue for now, @esakal if you are going to keep perusing this issue with the `electronjs` team I would appreciate it if you will keep us in the loop.

**Closed by bennymeg** 2020-11-08 20:54 UTC
Labels: bug, help wanted

**Comment by SolarIceMedia** [comment] 2020-11-17 04:36
try this, it seems to work so far for me, but haven't done extensive testing. the nx tooling system seems to ignore it if you put a package.json at the root of your app and still uses the main one at the root of the repo. setting the name in a second one at the app level seems to work for me on Linux at least. just only put the bare needed fields for electron it (ie no dependencies, no scripts, etc)

**Comment by SolarIceMedia** [comment] 2020-11-17 04:43
actually more I think about it, I wonder if its the way the "boilerplate" scripts (vue create, ng new, create-react-app, etc) setup webpack that's ignoring it during dev (while running the hot-reload server). the angular project I've been working with is a project from GitHub with a bunch of config changes, including a custom webpack config override, and it picks up the name during serve

**Comment by SolarIceMedia** [comment] 2020-11-17 08:09
https://github.com/electron-userland/electron-webpack/issues/239 this is where I found the during dev issue, still not finding a proper fix for it, but it is def related to web pack
